version: 2

sources:
  - name: raw
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
    tables:
      - name: RAW_CUSTOMERS
      - name: RAW_ORDERS
      - name: RAW_PAYMENTS
